// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const SAVE_DOMAIN = 'SAVE_DOMAIN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'
export const REGISTER_USER_MSG = 'REGISTER_USER_MSG'
export const CHANGE_BRANCH = 'CHANGE_BRANCH'

